name: metalaltion_motifs_env
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - conda-forge::python=3.7
  - conda-forge::pip
  - pytorch::pytorch=1.12.*
  - pip:
      - biopython==1.79
      - numpy==1.21.2
      - PyYAML==5.4.1
      - pandas